name: Dev
title: Dev Document

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

theme: jekyll-theme-primer

collections:
  docs:
    output: true

defaults:
  - scope:
      type: "docs"
    values:
      layout: "default"
      status: "temporary"
