title: たたかうやつ(仮)開発用資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

timezone: Asia/Tokyo
encoding: utf-8

theme: jekyll-theme-primer

collections:
  specs:
    output: true

defaults:
  - scope:
      type: specs
    values:
      layout: specs
      fix: false
  - scope:
      type: posts
    values:
      layout: wtitle
