title: たたかうやつ(仮)プランBテスト版の開発用資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

theme: jekyll-theme-primer

collections:
  temp:
    output: true
  fix:
    output: true
  impl:
    output: true

defaults:
  - scope:
      type: ""
    values:
      layout: "default"
