title: たたかうやつ(仮)資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

timezone: Asia/Tokyo
lang: ja-JP
encoding: utf-8

theme: jekyll-theme-primer

collections:
  specs:
    output: true

relative_links:
  enabled:     true
  collections: true

defaults:
  - scope:
      type: specs
    values:
      layout: specs
      fix: false
  - scope:
      type: posts
    values:
      layout: blogs
