title: たたかうやつ(仮)プランBテスト版の開発用資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

timezone: Asia/Tokyo
encoding: utf-8

theme: jekyll-theme-primer

collections:
  temp:
    output: true
  fix:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  # - scope:
  #     type: "temp"
  #   values:
  #     layout: "docs"
  # - scope:
  #     type: "fix"
  #   values:
  #     layout: "docs"
