title: たたかうやつ(仮)開発用資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

timezone: Asia/Tokyo
encoding: utf-8

theme: jekyll-theme-primer

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
