name: Dev
title: Dev Document

markdown: CommonMarkGhPages
theme: jekyll-theme-primer

collections:
  docs:
    output: true

defaults:
  - scope:
      type: "docs"
    values:
      layout: "default"
