name: Dev
title: Dev Document

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

theme: jekyll-theme-primer

collections:
  docs:
    output: true

defaults:
  - scope:
      type: "docs"
    values:
      layout: "default"
