theme: minima

name: Netsuretsu Touki Vivid Riser
title: Netsuretsu Touki Vivid Riser Dev Document

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: page
