title: たたかうやつ(仮)プランBテスト版の開発用資料集

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table

theme: jekyll-theme-primer

collections:
  temp:
    output: true
  fix:
    output: true

defaults:
  - scope:
      type: "temp"
    values:
      layout: "docs"
  - scope:
      type: "fix"
    values:
      layout: "docs"
